### ISSUE TITLE
custom pouch error on startup fails to load editor

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1450]
This is a non deterministic load issue. The editor is unusable afterwards.

![image](https://cloud.githubusercontent.com/assets/4175913/23406435/cfd336ae-fd73-11e6-8a21-6d49c13c10e8.png)

```
"{"status":409,"name":"conflict","message":"Document update conflict"}
    (No stack trace)
From previous event:
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:28623:19)
    at PouchDB.put (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:8054:18)
    at https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:3635:60
From previous event:
    at Table.setAsync (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:3635:29)
    at https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:3629:26
From previous event:
    at Table.forceSetAsync (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:3627:14)
    at Host.cacheStoreAsync (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:6261:26)
    at https://pxt.azureedge.net/blob/30be43c168078cb1d917adec76211772f8069d0d/pxtlib.js:3374:33
From previous event:
    at recordGetAsync (https://pxt.azureedge.net/blob/30be43c168078cb1d917adec76211772f8069d0d/pxtlib.js:3361:18)
    at https://pxt.azureedge.net/blob/30be43c168078cb1d917adec76211772f8069d0d/pxtlib.js:3403:28
From previous event:
    at Object.getHexInfoAsync (https://pxt.azureedge.net/blob/30be43c168078cb1d917adec76211772f8069d0d/pxtlib.js:3390:18)
    at Host.getHexInfoAsync (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:6258:24)
    at https://pxt.azureedge.net/blob/30be43c168078cb1d917adec76211772f8069d0d/pxtlib.js:1792:36
From previous event:
    at MainPackage.getCompileOptionsAsync (https://pxt.azureedge.net/blob/30be43c168078cb1d917adec76211772f8069d0d/pxtlib.js:1784:18)
    at typecheckAsync (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:2880:25)
    at waitForFirstTypecheckAsync (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:2860:16)
    at getApisInfoAsync (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:2895:12)
    at Object.getBlocksAsync (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:2902:11)
    at Editor.domUpdate (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:1684:47)
    at ProjectView.componentDidUpdate (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:176:21)
    at CallbackQueue.notifyAll (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:42745:22)
    at ReactReconcileTransaction.close (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:54864:26)
    at ReactReconcileTransaction.closeAll (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:57704:25)
    at ReactReconcileTransaction.perform (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:57651:16)
    at ReactUpdatesFlushTransaction.perform (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:57638:20)
    at ReactUpdatesFlushTransaction.perform (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:55697:38)
    at Object.flushBatchedUpdates (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:55758:19)
    at Object.wrapper [as flushBatchedUpdates] (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:54344:21)
    at ReactDefaultBatchingStrategyTransaction.closeAll (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:57704:25)
    at ReactDefaultBatchingStrategyTransaction.perform (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:57651:16)
    at Object.batchedUpdates (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:50424:19)
    at Object.enqueueUpdate (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:55787:22)
From previous event:
    at ProjectView.updateEditorFile (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:323:19)
    at ProjectView.renderCore (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:1157:18)
    at ProjectView.Component.render (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:3551:21)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:47890:34)
    at ReactCompositeComponentWrapper._renderValidatedComponent (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:47910:32)
    at ReactCompositeComponentWrapper.wrapper [as _renderValidatedComponent] (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:54344:21)
    at ReactCompositeComponentWrapper._updateRenderedComponent (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:47863:36)
    at ReactCompositeComponentWrapper._performComponentUpdate (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:47847:10)
    at ReactCompositeComponentWrapper.updateComponent (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:47776:12)
    at ReactCompositeComponentWrapper.wrapper [as updateComponent] (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:54344:21)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:47724:12)
    at Object.performUpdateIfNecessary (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:55037:22)
    at runBatchedUpdates (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:55740:21)
    at ReactReconcileTransaction.perform (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:57638:20)
    at ReactUpdatesFlushTransaction.perform (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:57638:20)
    at ReactUpdatesFlushTransaction.perform (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:55697:38)
    at Object.flushBatchedUpdates (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:55758:19)
    at Object.wrapper [as flushBatchedUpdates] (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:54344:21)
From previous event:
    at ProjectView.loadHeaderAsync (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:457:14)
    at https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:1555:30
From previous event:
    at HTMLDocument.<anonymous> (https://pxt.azureedge.net/blob/0a10d1004f718351b39af2af4f0fc229ddd5ca35/main.js:1531:10)
    at fire (https://pxt.azureedge.net/blob/5c3c456ac484e2f7244a7e8d16578d77eb218373/jquery.js:3187:31)
    at Object.fireWith [as resolveWith] (https://pxt.azureedge.net/blob/5c3c456ac484e2f7244a7e8d16578d77eb218373/jquery.js:3317:7)
    at Function.ready (https://pxt.azureedge.net/blob/5c3c456ac484e2f7244a7e8d16578d77eb218373/jquery.js:3536:13)
    at HTMLDocument.completed (https://pxt.azureedge.net/blob/5c3c456ac484e2f7244a7e8d16578d77eb218373/jquery.js:3552:9)"
```

**Comment by pelikhan** [comment]
The issue occurs when switching between versions of the same editor. Not blocking RC.

**Comment by abchatra** [comment]
Don't repro for me
