### ISSUE TITLE
Better message when destructuring an array

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#157]
It is explicitly documented that the compiler doesn't support desctructuring, however the error message for the following could be more helpful:

```typescript
let[x, y, ... rest] = [1, 2, 3, 4]
```

In browser: `undefined is not an object (evaluating 'symbol.flags')`

Console:

```
TypeError: Cannot read property 'flags' of undefined
    at getTypeOfSymbol (/Users/thomas/GitHub/pxt/built/pxt.js:17341:23)
    at Object.getTypeOfNode [as getTypeAtLocation] (/Users/thomas/GitHub/pxt/built/pxt.js:28762:24)
    at typeOf (/Users/thomas/GitHub/pxt/built/pxt.js:60870:29)
    at typeCheckVar (/Users/thomas/GitHub/pxt/built/pxt.js:61043:21)
    at emitVariableDeclaration (/Users/thomas/GitHub/pxt/built/pxt.js:62188:17)
    at emitNodeCore (/Users/thomas/GitHub/pxt/built/pxt.js:62286:32)
    at catchErrors (/Users/thomas/GitHub/pxt/built/pxt.js:62233:33)
    at emit (/Users/thomas/GitHub/pxt/built/pxt.js:62260:17)
    at Array.forEach (native)
    at emitVariableStatement (/Users/thomas/GitHub/pxt/built/pxt.js:62014:51)
    at emitNodeCore (/Users/thomas/GitHub/pxt/built/pxt.js:62269:32)
    at catchErrors (/Users/thomas/GitHub/pxt/built/pxt.js:62233:33)
    at emit (/Users/thomas/GitHub/pxt/built/pxt.js:62260:17)
    at Array.forEach (native)
    at emitBlock (/Users/thomas/GitHub/pxt/built/pxt.js:62009:33)
    at emitNodeCore (/Users/thomas/GitHub/pxt/built/pxt.js:62284:32)
```

**Comment by thomasdenney** [comment]
Fixed by https://github.com/Microsoft/pxt/pull/165

**Comment by tballmsft** [comment]
Please close if it is fixed.
