### ISSUE TITLE
Assert in compileExpression

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1609]
Correlation ID: ``KWnOR``

```
Error:
   at assert (at assert (https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js:206:23): https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js: 206)
   at compileExpression (at compileExpression (https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js:633:13): https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js: 633)
   at compileControlsIf (at compileControlsIf (https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js:751:28): https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js: 751)
   at compileStatementBlock (at compileStatementBlock (https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js:1008:25): https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js: 1008)
   at compileStatements (at compileStatements (https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js:1052:35): https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js: 1052)
   at compileEvent (at compileEvent (https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js:975:24): https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js: 975)
   at compileCall (at compileCall (https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js:892:24): https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js: 892)
   at compileStatementBlock (at compileStatementBlock (https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js:1035:30): https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js: 1035)
   at compileStatements (at compileStatements (https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js:1052:35): https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js: 1052)
   at <no_method> (at https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js:1211:40: https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js: 1211)
   at compileWorkspace (at compileWorkspace (https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js:1207:27): https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js: 1207)
   at Object.compile (at Object.compile (https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js:1307:30): https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js: 1307)
   at Editor.saveToTypeScript (at Editor.saveToTypeScript (https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js:1725:49): https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js: 1725)
   at <no_method> (at https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js:776:36: https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js: 776)
   at tryCatcher (at tryCatcher (https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js:13799:23): https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js: 13799)
```

**Comment by pelikhan** [comment]
This is our #1 reported crash.
