### ISSUE TITLE
Undefined reference in tokenize

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1610]
Correlation ID: b6MEV

```
TypeError:
   at tokenize (at tokenize (https://pxt.azureedge.net/blob/cfb40a77c5276b65128ee8f81c8b876ff3984075/pxtlib.js:13966:59): https://pxt.azureedge.net/blob/cfb40a77c5276b65128ee8f81c8b876ff3984075/pxtlib.js: 13966)
   at Object.format (at Object.format (https://pxt.azureedge.net/blob/cfb40a77c5276b65128ee8f81c8b876ff3984075/pxtlib.js:14579:21): https://pxt.azureedge.net/blob/cfb40a77c5276b65128ee8f81c8b876ff3984075/pxtlib.js: 14579)
   at tdASTtoTS (at tdASTtoTS (https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js:1416:27): https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js: 1416)
   at Object.compile (at Object.compile (https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js:1307:20): https://pxt.azureedge.net/blob/6ba5c41996674ef1d0a98a5229dfdc6918610e83/pxtblocks.js: 1307)
   at Editor.saveToTypeScript (at Editor.saveToTypeScript (https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js:1725:49): https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js: 1725)
   at <no_method> (at https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js:776:36: https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js: 776)
   at tryCatcher (at tryCatcher (https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js:13799:23): https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js: 13799)
   at Promise._settlePromiseFromHandler (at Promise._settlePromiseFromHandler (https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js:11822:31): https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js: 11822)
   at Promise._settlePromise (at Promise._settlePromise (https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js:11879:18): https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js: 11879)
   at Promise._settlePromise0 (at Promise._settlePromise0 (https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js:11924:10): https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js: 11924)
   at Promise._settlePromises (at Promise._settlePromises (https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js:12003:18): https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js: 12003)
   at <no_method> (at https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js:8759:25: https://pxt.azureedge.net/blob/2ef59476fba2a669a4c667603646a2026b0a9961/main.js: 8759)
```

**Comment by abchatra** [comment]
@pelikhan What is the product impact here?

**Comment by abchatra** [comment]
Won't fix.
