### ISSUE TITLE
Run pxt inside Docker container

### ISSUE THREAD

**Issue by olemis** [Microsoft/pxt#2176]
Implement a Dockerfile script to build a container running PXT . Further details TBD .

**Comment by eduardobcastro** [comment]
Tried to make one but too many build errors occur

```
Step 1/7 : FROM node:9.5-stretch
 ---> bd7d944d0ab9
Step 2/7 : WORKDIR /home/node
 ---> Using cache
 ---> daa43f5ea3e3
Step 3/7 : COPY pxt ./pxt/
 ---> acaa2db1ad69
Step 4/7 : RUN chown -R node:node .
 ---> Running in 42ad6a06537e
Removing intermediate container 42ad6a06537e
 ---> 824793351125
Step 5/7 : USER node
 ---> Running in 80c9f11ff087
Removing intermediate container 80c9f11ff087
 ---> e3b22f30f80a
Step 6/7 : WORKDIR /home/node/pxt
Removing intermediate container d913f707c61c
 ---> 5d9948f0e794
Step 7/7 : RUN npm install
 ---> Running in acb300454e6c

> sqlite3@3.1.13 install /home/node/pxt/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/home/node/pxt/node_modules/sqlite3/lib/binding/node-v59-linux-x64/node_sqlite3.node" is installed via remote

> ttf2woff2@2.0.3 install /home/node/pxt/node_modules/ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)


> leveldown@1.4.6 install /home/node/pxt/node_modules/leveldown
> prebuild --install

prebuild info begin Prebuild version 4.5.0
prebuild info looking for local prebuild @ prebuilds/leveldown-v1.4.6-node-v59-linux-x64.tar.gz
prebuild info looking for cached prebuild @ /home/node/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.4.6-leveldown-v1.4.6-node-v59-linux-x64.tar.gz
prebuild http request GET https://github.com/level/leveldown/releases/download/v1.4.6/leveldown-v1.4.6-node-v59-linux-x64.tar.gz
prebuild http 404 https://github.com/level/leveldown/releases/download/v1.4.6/leveldown-v1.4.6-node-v59-linux-x64.tar.gz
prebuild WARN install No prebuilt binaries found (target=v9.5.0 arch=x64 platform=linux)
prebuild info install We will now try to compile from source.
prebuild verb starting node-gyp process
prebuild verb execute node-gyp with `node index.js rebuild --target=v9.5.0 --target_arch=x64`
prebuild verb ok
prebuild verb ok
prebuild verb ok
make: Entering directory '/home/node/pxt/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/leveldb_main.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/hash.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/env_posix.o
  AR(target) Release/obj.target/deps/leveldb/leveldb.a
  COPY Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
In file included from ../node_modules/nan/nan.h:190:0,
                 from ../src/batch.cc:3:
../node_modules/nan/nan_maybe_43_inl.h: In function 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)':
../node_modules/nan/nan_maybe_43_inl.h:88:64: warning: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
                                                                ^
In file included from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:26:0,
                 from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/node.h:63,
                 from ../src/batch.cc:1:
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:3115:29: note: declared here
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/batch.cc: In static member function 'static v8::Local<v8::Value> leveldown::Batch::NewInstance(v8::Local<v8::Object>, v8::Local<v8::Object>)':
../src/batch.cc:71:69: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
     instance = constructorHandle->GetFunction()->NewInstance(1, argv);
                                                                     ^
In file included from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:26:0,
                 from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/node.h:63,
                 from ../src/batch.cc:1:
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:3844:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/batch.cc:74:69: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
     instance = constructorHandle->GetFunction()->NewInstance(2, argv);
                                                                     ^
In file included from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:26:0,
                 from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/node.h:63,
                 from ../src/batch.cc:1:
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:3844:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  CXX(target) Release/obj.target/leveldown/src/batch_async.o
In file included from ../node_modules/nan/nan.h:190:0,
                 from ../src/database.h:16,
                 from ../src/batch.h:9,
                 from ../src/batch_async.cc:8:
../node_modules/nan/nan_maybe_43_inl.h: In function 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)':
../node_modules/nan/nan_maybe_43_inl.h:88:64: warning: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
                                                                ^
In file included from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:26:0,
                 from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/node.h:63,
                 from ../src/batch.h:5,
                 from ../src/batch_async.cc:8:
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:3115:29: note: declared here
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  CXX(target) Release/obj.target/leveldown/src/database.o
In file included from ../node_modules/nan/nan.h:190:0,
                 from ../src/leveldown.h:11,
                 from ../src/database.cc:12:
../node_modules/nan/nan_maybe_43_inl.h: In function 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)':
../node_modules/nan/nan_maybe_43_inl.h:88:64: warning: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
                                                                ^
In file included from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:26:0,
                 from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/node.h:63,
                 from ../src/database.cc:6:
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:3115:29: note: declared here
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/database.cc: In static member function 'static v8::Local<v8::Value> leveldown::Database::NewInstance(v8::Local<v8::String>&)':
../src/database.cc:166:67: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   instance = constructorHandle->GetFunction()->NewInstance(1, argv);
                                                                   ^
In file included from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:26:0,
                 from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/node.h:63,
                 from ../src/database.cc:6:
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:3844:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/database.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE leveldown::Database::Iterator(Nan::NAN_METHOD_ARGS_TYPE)':
../src/database.cc:458:16: warning: 'v8::TryCatch::TryCatch()' is deprecated: Use isolate version [-Wdeprecated-declarations]
   v8::TryCatch try_catch;
                ^~~~~~~~~
In file included from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:26:0,
                 from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/node.h:63,
                 from ../src/database.cc:6:
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:8343:40: note: declared here
   V8_DEPRECATED("Use isolate version", TryCatch());
                                        ^
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  CXX(target) Release/obj.target/leveldown/src/database_async.o
In file included from ../node_modules/nan/nan.h:190:0,
                 from ../src/database.h:16,
                 from ../src/database_async.cc:12:
../node_modules/nan/nan_maybe_43_inl.h: In function 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)':
../node_modules/nan/nan_maybe_43_inl.h:88:64: warning: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
                                                                ^
In file included from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:26:0,
                 from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/node.h:63,
                 from ../src/database_async.cc:6:
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:3115:29: note: declared here
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  CXX(target) Release/obj.target/leveldown/src/iterator.o
In file included from ../node_modules/nan/nan.h:190:0,
                 from ../src/database.h:16,
                 from ../src/iterator.cc:9:
../node_modules/nan/nan_maybe_43_inl.h: In function 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)':
../node_modules/nan/nan_maybe_43_inl.h:88:64: warning: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
                                                                ^
In file included from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:26:0,
                 from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/node.h:63,
                 from ../src/iterator.cc:6:
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:3115:29: note: declared here
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/iterator.cc: In static member function 'static v8::Local<v8::Object> leveldown::Iterator::NewInstance(v8::Local<v8::Object>, v8::Local<v8::Number>, v8::Local<v8::Object>)':
../src/iterator.cc:331:69: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
     instance = constructorHandle->GetFunction()->NewInstance(2, argv);
                                                                     ^
In file included from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:26:0,
                 from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/node.h:63,
                 from ../src/iterator.cc:6:
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:3844:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/iterator.cc:334:69: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
     instance = constructorHandle->GetFunction()->NewInstance(3, argv);
                                                                     ^
In file included from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:26:0,
                 from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/node.h:63,
                 from ../src/iterator.cc:6:
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:3844:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  CXX(target) Release/obj.target/leveldown/src/iterator_async.o
In file included from ../node_modules/nan/nan.h:190:0,
                 from ../src/database.h:16,
                 from ../src/iterator_async.cc:9:
../node_modules/nan/nan_maybe_43_inl.h: In function 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)':
../node_modules/nan/nan_maybe_43_inl.h:88:64: warning: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
                                                                ^
In file included from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:26:0,
                 from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/node.h:63,
                 from ../src/iterator_async.cc:6:
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:3115:29: note: declared here
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  CXX(target) Release/obj.target/leveldown/src/leveldown.o
In file included from ../node_modules/nan/nan.h:190:0,
                 from ../src/leveldown.h:11,
                 from ../src/leveldown.cc:8:
../node_modules/nan/nan_maybe_43_inl.h: In function 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)':
../node_modules/nan/nan_maybe_43_inl.h:88:64: warning: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
                                                                ^
In file included from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:26:0,
                 from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/node.h:63,
                 from ../src/leveldown.cc:6:
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:3115:29: note: declared here
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  CXX(target) Release/obj.target/leveldown/src/leveldown_async.o
In file included from ../node_modules/nan/nan.h:190:0,
                 from ../src/leveldown.h:11,
                 from ../src/leveldown_async.cc:8:
../node_modules/nan/nan_maybe_43_inl.h: In function 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)':
../node_modules/nan/nan_maybe_43_inl.h:88:64: warning: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
                                                                ^
In file included from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:26:0,
                 from /home/node/pxt/node_modules/leveldown/9.5.0/include/node/node.h:63,
                 from ../src/leveldown.h:8,
                 from ../src/leveldown_async.cc:8:
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8.h:3115:29: note: declared here
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/node/pxt/node_modules/leveldown/9.5.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/leveldown.node
  COPY Release/leveldown.node
make: Leaving directory '/home/node/pxt/node_modules/leveldown/build'
prebuild verb ok
prebuild verb done node-gyp'ing

> keytar@4.2.1 install /home/node/pxt/node_modules/keytar
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/keytar-v4.2.1-node-v59-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/node/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v59-linux-x64.tar.gz
prebuild-install http request GET https://github.com/atom/node-keytar/releases/download/v4.2.1/keytar-v4.2.1-node-v59-linux-x64.tar.gz
prebuild-install http 200 https://github.com/atom/node-keytar/releases/download/v4.2.1/keytar-v4.2.1-node-v59-linux-x64.tar.gz
prebuild-install info downloading to @ /home/node/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v59-linux-x64.tar.gz.1556-d9155221c814d.tmp
prebuild-install info renaming to @ /home/node/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v59-linux-x64.tar.gz
prebuild-install info unpacking @ /home/node/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v59-linux-x64.tar.gz
prebuild-install info unpack resolved to /home/node/pxt/node_modules/keytar/build/Release/keytar.node
prebuild-install WARN install libsecret-1.so.0: cannot open shared object file: No such file or directory
Package libsecret-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsecret-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsecret-1' found
gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.9.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node/pxt/node_modules/keytar
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> node-hid@0.5.7 install /home/node/pxt/node_modules/node-hid
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/node-hid-v0.5.7-node-v59-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/node/.npm/_prebuilds/https-github.com-node-hid-node-hid-releases-download-v0.5.7-node-hid-v0.5.7-node-v59-linux-x64.tar.gz
prebuild-install http request GET https://github.com/node-hid/node-hid/releases/download/v0.5.7/node-hid-v0.5.7-node-v59-linux-x64.tar.gz
prebuild-install http 404 https://github.com/node-hid/node-hid/releases/download/v0.5.7/node-hid-v0.5.7-node-v59-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.5.0 runtime=node arch=x64 platform=linux)
make: Entering directory '/home/node/pxt/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
 #include <libusb.h>
                    ^
compilation terminated.
make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1
hidapi.target.mk:97: recipe for target 'Release/obj.target/hidapi/hidapi/libusb/hid.o' failed
make: Leaving directory '/home/node/pxt/node_modules/node-hid/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.9.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node/pxt/node_modules/node-hid
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> serialport@6.1.1 install /home/node/pxt/node_modules/serialport
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/serialport-v6.1.1-node-v59-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/node/.npm/_prebuilds/https-github.com-node-serialport-node-serialport-releases-download-v6.1.1-serialport-v6.1.1-node-v59-linux-x64.tar.gz
prebuild-install http request GET https://github.com/node-serialport/node-serialport/releases/download/v6.1.1/serialport-v6.1.1-node-v59-linux-x64.tar.gz
prebuild-install http 200 https://github.com/node-serialport/node-serialport/releases/download/v6.1.1/serialport-v6.1.1-node-v59-linux-x64.tar.gz
prebuild-install info downloading to @ /home/node/.npm/_prebuilds/https-github.com-node-serialport-node-serialport-releases-download-v6.1.1-serialport-v6.1.1-node-v59-linux-x64.tar.gz.1621-5feeee8634f67.tmp
prebuild-install info renaming to @ /home/node/.npm/_prebuilds/https-github.com-node-serialport-node-serialport-releases-download-v6.1.1-serialport-v6.1.1-node-v59-linux-x64.tar.gz
prebuild-install info unpacking @ /home/node/.npm/_prebuilds/https-github.com-node-serialport-node-serialport-releases-download-v6.1.1-serialport-v6.1.1-node-v59-linux-x64.tar.gz
prebuild-install info unpack resolved to /home/node/pxt/node_modules/serialport/build/Release/serialport.node
prebuild-install info unpack required /home/node/pxt/node_modules/serialport/build/Release/serialport.node successfully
prebuild-install info install Successfully installed prebuilt binary!
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: keytar@4.2.1 (node_modules/keytar):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: keytar@4.2.1 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-hid@0.5.7 (node_modules/node-hid):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-hid@0.5.7 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```
