### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getShowLines' of null

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#2352]
Exception: Uncaught TypeError: Cannot read property 'getShowLines' of null

Repro: 
1. load the Editor
2. Open any category flyout
2. Switch to Javascript
3. Switch back to Blocks
You get the Exception.. 

```
main.js:9896 Uncaught TypeError: Cannot read property 'getShowLines' of null
    at Blockly.Toolbox.TreeNode.goog.ui.tree.BaseNode.getExpandIconClass (https://pxt.azureedge.net/blob/c5c66199ca244933c13c3206279bb128ed9f6957/blockly/blockly_compressed.js:959:88)
    at Blockly.Toolbox.TreeNode.goog.ui.tree.BaseNode.updateExpandIcon (https://pxt.azureedge.net/blob/c5c66199ca244933c13c3206279bb128ed9f6957/blockly/blockly_compressed.js:967:116)
    at Blockly.Toolbox.TreeNode.goog.ui.tree.BaseNode.setExpanded (https://pxt.azureedge.net/blob/c5c66199ca244933c13c3206279bb128ed9f6957/blockly/blockly_compressed.js:951:199)
    at collapseSubcategories (https://pxt.azureedge.net/blob/7d0ff74e3c149d800d693babad1ee0247510405f/pxtblocks.js:3614:25)
    at Blockly.Toolbox.TreeControl.setSelectedItem (https://pxt.azureedge.net/blob/7d0ff74e3c149d800d693babad1ee0247510405f/pxtblocks.js:3585:21)
    at Editor.updateToolbox (https://pxt.azureedge.net/blob/07a1d9afe05ad8edeff31777260948d56930d7b8/main.js:2650:40)
    at https://pxt.azureedge.net/blob/07a1d9afe05ad8edeff31777260948d56930d7b8/main.js:2109:23
```

**Comment by microsoftsam** [comment]
Only repro's on master.
