### ISSUE TITLE
Regression in adding certain packages

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#2716]
Bug in adding the sonar package on the micro:bit yields the following error: 

```
Uncaught TypeError: Cannot read property 'replace' of null
    at Function.b.fadeColour (https://pxt.azureedge.net/blob/f18fda6ee99e040d0478bb329470a321c7cb247c/blockly/blockly_compressed.js:1694:139)
    at appendNamespaceCss (https://pxt.azureedge.net/blob/7800799a7071ae92302fe70245ee15a1c64ae4b8/pxtblocks.js:2628:188)
    at createToolbox (https://pxt.azureedge.net/blob/7800799a7071ae92302fe70245ee15a1c64ae4b8/pxtblocks.js:3198:21)
    at Object.initBlocks (https://pxt.azureedge.net/blob/7800799a7071ae92302fe70245ee15a1c64ae4b8/pxtblocks.js:3341:22)
    at https://pxt.azureedge.net/blob/4f361dff26d397350d166a0e0319cad2712690d8/main.js:2137:40
    at <anonymous>
```

Seems related to the docs inline block changes.

**Comment by microsoftsam** [comment]
Looks like packages with no colors break
