### ISSUE TITLE
Browser throws an error when runing pxt serve for pxt-microbit

### ISSUE THREAD

**Issue by lian1925** [Microsoft/pxt#2955]
Following the instructions in the pxt-microbit README, after running `pxt serve`, chrome browser is opened but it throw some error on the browser's console as follow:

```
GET http://localhost:3232/blb/target.js 404
Uncaught TypeError: Cannot read property 'pxtCrowdinBranch' of undefined
    at http://localhost:3232/blb/main.js:1925:122
    at <anonymous>
From previous event:
    at HTMLDocument.<anonymous> (http://localhost:3232/blb/main.js:1914:10)
    at i (http://localhost:3232/blb/jquery.js:2:27151)
    at Object.fireWith [as resolveWith] (http://localhost:3232/blb/jquery.js:2:27914)
    at Function.ready (http://localhost:3232/blb/jquery.js:2:29707)
    at HTMLDocument.J (http://localhost:3232/blb/jquery.js:2:29892)
```

**Comment by samelhusseini** [comment]
Make sure you're using the v0 branch of pxt when running pxt serve for the microbit target.
