### ISSUE TITLE
Following pxt-microbit readme  throws an error at pxt serve

### ISSUE THREAD

**Issue by lian1925** [Microsoft/pxt#3027]
Trying to get a pxt dev environment set up so I can create my own target, starting by trying pxt-microbit.

Following the instructions in the pxt-microbit README gives the following output when running pxt serve:
```
huahuadeMacBook-Air:pxt-microbit huahua$ pxt serve
Could not determine target's pxt-core location, falling back to default: /Users/huahua/Documents/我的目录/lian/pxt-microbit/node_modules/pxt-core
Using target PXT/microbit with build engine yotta
  Target dir:   /Users/huahua/Documents/我的目录/lian/pxt-microbit
  PXT Core dir: /Users/huahua/Documents/我的目录/lian/pxt-microbit/node_modules/pxt-core
building sim...
[run] cd sim; node ../node_modules/typescript/bin/tsc
log strings: 63 files; 0 strings -> sim-strings.json
Could not determine target's pxt-core location, falling back to default: /Users/huahua/Documents/我的目录/lian/pxt-microbit/node_modules/pxt-core
building target.json in /Users/huahua/Documents/我的目录/lian/pxt-microbit...
building libs/core
  skip native build of non-project
building libs/radio
  skip native build of non-project
building libs/devices
  skip native build of non-project
building libs/bluetooth
  skip native build of non-project
building libs/blocksprj
*** yotta target bbc-microbit-classic-gcc
Fatal Exception, yotta=0.18.2
Traceback (most recent call last):
  File "/usr/local/bin/yotta", line 4, in <module>
    yotta.main()
  File "/usr/local/lib/python2.7/site-packages/yotta/main.py", line 61, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/yotta/main.py", line 46, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/yotta/main.py", line 244, in main
    status = args.command(args, following_args)
  File "/usr/local/lib/python2.7/site-packages/yotta/target.py", line 126, in execCommand
    target, errors = c.satisfyTarget(t)
  File "/usr/local/lib/python2.7/site-packages/yotta/lib/component.py", line 688, in satisfyTarget
    shrinkwrap = self.getShrinkwrap()
  File "/usr/local/lib/python2.7/site-packages/yotta/lib/target.py", line 166, in getDerivedTarget
    inherit_shrinkwrap = shrinkwrap
  File "/usr/local/lib/python2.7/site-packages/yotta/lib/access.py", line 391, in satisfyVersion
    inherit_shrinkwrap = inherit_shrinkwrap
  File "/usr/local/lib/python2.7/site-packages/yotta/lib/access.py", line 284, in satisfyVersionFromSearchPaths
    inherit_shrinkwrap = inherit_shrinkwrap
  File "/usr/local/lib/python2.7/site-packages/yotta/lib/access.py", line 218, in searchPathsFor
    check_path = os.path.join(path, name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 24: ordinal not in range(128)

***
*** Build failed: target build failed: yotta target bbc-microbit-classic-gcc: exit code 1
Error: yotta target bbc-microbit-classic-gcc: exit code 1
    at ChildProcess.<anonymous> (/Users/huahua/Documents/我的目录/lian/pxt-microbit/node_modules/pxt-core/built/buildengine.js:144:24)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
***
```
Besides, my enviroment is node v8.5.0 , OS X 10.10.5

**Comment by baradaran** [comment]
Have you tried following this? 
https://makecode.com/cli
