### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by beenotung** [Microsoft/pxt#3301]
I tried to run it on a bare windows, with new installed nodejs (v8) and 'git for windows',

Suggestion: to add tsconfig.json and indicate es2015 or more in the lib field

log file:
[2017-10-21T03_29_30_115Z-debug.log](https://github.com/Microsoft/pxt/files/1403736/2017-10-21T03_29_30_115Z-debug.log)

runtime output:
```
D:\pxt>npm start

> pxt-core@2.2.20 start D:\pxt
> jake default

[built/pxtcompiler.js] cd pxtcompiler; node ../node_modules/typescript/bin/tsc
[built/pxtsim.js] cd pxtsim; node ../node_modules/typescript/bin/tsc
instructions.ts(1,1): error TS6053: File '../typings/globals/bluebird/index.d.ts
' not found.
langsupport.ts(559,33): error TS2304: Cannot find name 'Promise'.
runtime.ts(1,1): error TS6053: File '../typings/globals/bluebird/index.d.ts' not
 found.
runtime.ts(41,19): error TS2304: Cannot find name 'Promise'.
runtime.ts(84,53): error TS2304: Cannot find name 'Promise'.
runtime.ts(86,20): error TS2304: Cannot find name 'Promise'.
runtime.ts(264,24): error TS2304: Cannot find name 'Promise'.
runtime.ts(264,38): error TS7006: Parameter 'resolve' implicitly has an 'any' ty
pe.
runtime.ts(264,47): error TS7006: Parameter 'reject' implicitly has an 'any' typ
e.
simlib.ts(1,1): error TS6053: File '../typings/globals/bluebird/index.d.ts' not
found.
simlib.ts(141,24): error TS2304: Cannot find name 'Promise'.
simlib.ts(141,42): error TS7006: Parameter 'resolve' implicitly has an 'any' typ
e.
simlib.ts(141,51): error TS7006: Parameter 'reject' implicitly has an 'any' type
.
visuals/buttonpair.ts(1,1): error TS6053: File '../typings/globals/bluebird/inde
x.d.ts' not found.
visuals/genericboard.ts(1,1): error TS6053: File '../typings/globals/bluebird/in
dex.d.ts' not found.
runtime.ts(84,53): error TS4055: Return type of public method from exported clas
s has or is using private name 'Promise'.
jake aborted.
TypeError: task.fail is not a function
    at ChildProcess.ch.on (D:\pxt\jakeutil.js:106:18)
    at emitTwo (events.js:125:13)
(See full trace by running task with --trace)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pxt-core@2.2.20 start: `jake default`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pxt-core@2.2.20 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\compuser\AppData\Roaming\npm-cache\_logs\2017-10-21T03_29_
30_115Z-debug.log
```

**Comment by pelikhan** [comment]
You need to run  “typings install”

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by beenotung** [comment]
Oh thanks, so here's an suggestion https://github.com/Microsoft/pxt/pull/3303

**Comment by microsoftsam** [comment]
Closing, thanks @beenotung for your suggestion :)
