### ISSUE TITLE
Can't Build pxt when Linked to pxt-microbit

### ISSUE THREAD

**Issue by mayconkruger** [Microsoft/pxt#3388]
Hi, I've been trying to setup pxt targeting pxt-microbit.

I cloned  pxt and pxt-microbit in the same directory, went to pxt-microbit folder and executed: 
`npm link ../pxt`

I then installed all node dependencies(as it says in the pxt git README file):
`npm install -g jake
npm install -g typings
npm install -g pxt
typings install
`
But when I try to serve pxt-microbit by executing:
`jake serve`

The console trows the following errors:

**Using target PXT/microbit with build engine yotta
  Target dir:   C:\Users\mig\Projects\tmp\link_test\pxt-microbit
  PXT Core dir: C:\Users\mig\Projects\tmp\link_test\pxt
building node_modules/pxt-core...
[run] cd node_modules/pxt-core; jake.cmd
local pxt-core built.
error TS6053: File 'node_modules/typescript/lib/lib.d.ts' not found.
error TS2318: Cannot find global type 'Array'.
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.

***
*** Build failed: target build failed: Oops, typescript does not seem to be installed, did you run 'npm install'?
Error: Oops, typescript does not seem to be installed, did you run 'npm install'?
    at Object.userError (C:\Users\mig\Projects\tmp\link_test\pxt\built\pxt.js:54712:25)
    at buildFolderAsync (C:\Users\mig\Projects\tmp\link_test\pxt\built\pxt.js:81006:11)
    at C:\Users\mig\Projects\tmp\link_test\pxt\built\pxt.js:80986:36
    at tryCatcher (C:\Users\mig\Projects\tmp\link_test\pxt\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\mig\Projects\tmp\link_test\pxt\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\mig\Projects\tmp\link_test\pxt\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromiseCtx (C:\Users\mig\Projects\tmp\link_test\pxt\node_modules\bluebird\js\release\promise.js:606:10)
    at Async._drainQueue (C:\Users\mig\Projects\tmp\link_test\pxt\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\Users\mig\Projects\tmp\link_test\pxt\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\mig\Projects\tmp\link_test\pxt\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
***
**

I've tried doing the same process several times with the following branch combinations:
pxt  				master         
pxt-microbit		master

pxt  				v0.12.1     #this come from  https://github.com/Microsoft/pxt-microbit
pxt-microbit		v0.12.1

pxt  				v0.13.1        
pxt-microbit		v0.13.1

pxt 				v0.14.3  
pxt-microbit 		v0.13.28

But all trow the same error.
I am doing something wrong? Is there any known branch combination that would fix this?
Thanks in Advance.

**Comment by alexp3d** [comment]
Make sure you are using the correct pxt branch:v0

master branch pxt isn't stable as far as I know (I think it is used more as a dev branch...). v0 is the stable production branch.

**Comment by mayconkruger** [comment]
Sure, I tried some v0 versions already:
pxt v0.12.1 #this come from https://github.com/Microsoft/pxt-microbit
pxt-microbit v0.12.1

pxt v0.13.1
pxt-microbit v0.13.1

pxt v0.14.3
pxt-microbit v0.13.28

with no success.

**Comment by alexp3d** [comment]
This issue is likely an issue on Microsoft/pxt, not Microsoft/pxt-microbit. 

I was able to use pxt-microbit master branch. 

You must go to Microsoft/pxt and pull that (zip file here) https://github.com/Microsoft/pxt/archive/v0.zip

**Comment by mayconkruger** [comment]
After further investigation, i found a solution for the issue.

All I had to do was to manually install the following node_modules in  the pxt-microbit/node_modules folder.
-mime
-semantic-ui-less
-typescript
-less

I then executed 
`jake serve`
from the pxt folder, and was able to compile and run the project without any erros.

Thanks for the help!
