### ISSUE TITLE
pxt cli update fails

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt#3516]
Installed PXT cli a while ago following these steps:

```
sudo npm install -g pxt
mkdir pxtworkspace
cd pxtworkspace
npm install pxt-microbit --no-bin-links
pxt target microbit
```

From the `pxtworkspace` I can do `pxt serve` and works as expected:
```
> pxt serve
Using target PXT/microbit with build engine yotta
  Target dir:   /home/vagrant/vagrant_shared/pxtworkspace/node_modules/pxt-microbit
  PXT Core dir: /home/vagrant/vagrant_shared/pxtworkspace/node_modules/pxt-core
Going to /home/vagrant/vagrant_shared/pxtworkspace/node_modules/pxt-microbit
No sim/tsconfig.json; assuming npm installed package
Starting server in /home/vagrant/vagrant_shared/pxtworkspace/node_modules/pxt-microbit
With pxt core at /home/vagrant/vagrant_shared/pxtworkspace/node_modules/pxt-core
starting local ws server at 3233...
serial: monitoring ports...
serial: failed to load, skipping...
---------------------------------------------

To launch the editor, open this URL:
http://localhost:3232/#local_token=b68ab49b-d947-46d4-de6c-e8ed34f0dec2&wsport=3233

---------------------------------------------
```

Tried updating as indicated in https://makecode.com/cli (`npm update`) and https://makecode.com/cli/update (`pxt update`) and get the following errors:

```
> pxt update
Using target PXT/microbit with build engine yotta
  Target dir:   /home/vagrant/vagrant_shared/pxtworkspace/node_modules/pxt-microbit
  PXT Core dir: /home/vagrant/vagrant_shared/pxtworkspace/node_modules/pxt-core
[run] git pull
fatal: Not a git repository (or any parent up to mount point /home/vagrant/vagrant_shared)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
INTERNAL ERROR: Error: Exit code: 128 from git pull
    at ChildProcess.<anonymous> (/home/vagrant/vagrant_shared/pxtworkspace/node_modules/pxt-core/built/nodeutil.js:86:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
```

```
> npm update
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "update"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/pxtcli.json
npm ERR! 404
npm ERR! 404  'pxtcli.json' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/vagrant_shared/pxtworkspace/npm-debug.log
```

**Comment by riknoll** [comment]
That second error (`npm update`) is definitely our fault; we add a file called pxtcli.json into the `node_modules` directory of the target. You should be able to run `npm install` and get the desired effect.

As for the `pxt update` command; that's an internal command that we use for managing releases. All it does is check the git repo for `pxt-core` to determine what the latest pushed release is and update the version reference in the target's package.json.

I don't think you need it, but the reason it's failing is because it expects your `pxt-core` node module to be a git repository. That is normally the case when you are developing pxt locally (i.e. you cloned the pxt repo and ran `npm link ../pxt` from within `pxt-microbit`).

**Comment by riknoll** [comment]
Marking this as a bug because we really shouldn't break `npm update`.

**Comment by microbit-carlos** [comment]
Thanks @riknoll

**Comment by obulat** [comment]
I still get both errors. Is there a solution?

**Comment by riknoll** [comment]
@obulat The solution is to not use `pxt update` and use `npm install` instead of `npm update`. `pxt update` is really meant to be a secret command that is only used by the MakeCode developer team, it's pretty useless for anyone else. I hope that helps!
