### ISSUE TITLE
"INTERNAL ERROR" when running "pxt staticpkg"

### ISSUE THREAD

**Issue by sgk** [Microsoft/pxt#3612]
```
rendering docs/types/number.md
rendering docs/types/string.md
rendering docs/types/var.md
INTERNAL ERROR: TypeError: Cannot read property 'replace' of undefined
    at Object.renderMarkdown (/home/sgk/pxt/microbit/pxt/built/pxt.js:58890:32)
    at renderDocs (/home/sgk/pxt/microbit/pxt/built/pxt.js:81306:33)
    at /home/sgk/pxt/microbit/pxt/built/pxt.js:82945:34
```

**Comment by WinEcos** [comment]
@sgk  have you soved this issue ? thx
