### ISSUE TITLE
Regression: package.json is missing built/gitfs.js

### ISSUE THREAD

**Issue by matthewtebbs** [Microsoft/pxt#4072]
This module was recently added as a dependency but not included in the package files information.
With **3.8.4** upon running `pxt serve` I get this error which indicates an incomplete npm package.

```
matthew$ pxt serve
module.js:549
    throw err;
    ^

Error: Cannot find module './gitfs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/matthew/Source/git/MuddyTummy/pxt-Impetus/node_modules/pxt-core/built/pxt.js:129089:13)
```

**Comment by samelhusseini** [comment]
Have you tried doing a jake clean?

The CLI needs to rebuild.

**Comment by matthewtebbs** [comment]
This was an npm install. I suspect the package.json is missing a dep. True? Or my mistake. Could be.
