### ISSUE TITLE
td compilation error

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#415]
```
*** lchqfb.ts, size=14840
Error:   -> Line 1547 ('    b .cont.154 ; with expression'), error: assembly error
   Maybe: b     LABEL (argument out of range or mis-aligned at '.cont.154')
    at throwThumbErrors (/home/travis/build/Microsoft/pxt-microbit/node_modules/pxt-core/built/pxt.js:66502:27)
    at assemble (/home/travis/build/Microsoft/pxt-microbit/node_modules/pxt-core/built/pxt.js:66511:13)
    at Object.thumbEmit (/home/travis/build/Microsoft/pxt-microbit/node_modules/pxt-core/built/pxt.js:66545:23)
    at finalEmit (/home/travis/build/Microsoft/pxt-microbit/node_modules/pxt-core/built/pxt.js:62974:26)
    at catchErrors (/home/travis/build/Microsoft/pxt-microbit/node_modules/pxt-core/built/pxt.js:64862:33)
    at Object.compileBinary (/home/travis/build/Microsoft/pxt-microbit/node_modules/pxt-core/built/pxt.js:62820:17)
    at Object.compile (/home/travis/build/Microsoft/pxt-microbit/node_modules/pxt-core/built/pxt.js:65252:38)
    at compilesOK (/home/travis/build/Microsoft/pxt-microbit/node_modules/pxt-core/built/pxt.js:74866:20)
    at /home/travis/build/Microsoft/pxt-microbit/node_modules/pxt-core/built/pxt.js:74836:22
    at tryCatcher (/home/travis/build/Microsoft/pxt-microbit/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/Microsoft/pxt-microbit/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/travis/build/Microsoft/pxt-microbit/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/travis/build/Microsoft/pxt-microbit/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/travis/build/Microsoft/pxt-microbit/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/travis/build/Microsoft/pxt-microbit/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/home/travis/build/Microsoft/pxt-microbit/node_modules/bluebird/js/release/promise.js:453:14)
pxt_modules/microbit/dal.d.ts(1,1): error TS9200:   -> Line 1547 ('    b .cont.154 ; with expression'), error: assembly error
   Maybe: b     LABEL (argument out of range or mis-aligned at '.cont.154')
```

**Comment by tballmsft** [comment]
Thanks, @pelikhan  and @mmoskal  - do we have a regression test?

**Comment by mmoskal** [comment]
Well, the one above is a regression test run on build. You can run them using `travis-tests.sh`

I agree it should be there explicitly - I asked @whaleygeek (author or lchqfb) about contributing these and checking them in.
