### ISSUE TITLE
TS code generation bug for classes???

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#439]
Please sync up to avrcodegen, jake and then

node.js built\pxt.js

to see the error:

C:\Users\tball\Documents\GitHub\pxt\built\pxt.js:54205
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
                                                                   ^
TypeError: Cannot read property 'prototype' of undefined
    at __extends (C:\Users\tball\Documents\GitHub\pxt\built\pxt.js:54205:68)
    at C:\Users\tball\Documents\GitHub\pxt\built\pxt.js:59294:13
    at ts.pxtc.ts.pxtc (C:\Users\tball\Documents\GitHub\pxt\built\pxt.js:59327:10)
    at ts (C:\Users\tball\Documents\GitHub\pxt\built\pxt.js:59329:7)
    at Object.<anonymous> (C:\Users\tball\Documents\GitHub\pxt\built\pxt.js:59330:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10

It comes from the file backavr.ts, which simply defines a class. I am at a loss about the error.

**Comment by mmoskal** [comment]
You need to define classes in the right order. You can do that with `<reference...>` - just pushed a fix

**Comment by tballmsft** [comment]
Thanks, Michal.
