### ISSUE TITLE
Latest Version of pxt causes crash

### ISSUE THREAD

**Issue by wallarug** [microsoft/pxt#6536]
There is an issue in the v5.33.5 release of this repository that prevents me from running the pxt-maker code.   Issue occurred on clean install.  Last known good version is v5.32.4.

**To Reproduce**
from microsoft/pxt-maker:

```
pxt serve
```

Returns:

```
[23:32:38] Finished 'backendutils' after 2.51 s
C:/Users/cianb/Documents/repos/makecode-peter/pxt-maker/node_modules/pxt-core/built/pxtlib.d.ts(332,21): error TS2694: Namespace 'pxt' has no exported member 'workspace'.
C:/Users/cianb/Documents/repos/makecode-peter/pxt-maker/node_modules/pxt-core/built/pxtlib.d.ts(2637,16): error TS2304: Cannot find name 'JsonScriptMeta'.
pxtcompiler\emitter\service.ts(1074,95): error TS2345: Argument of type 'FunctionLike' is not assignable to parameter of type 'FunctionLikeDeclaration'.
  Type 'CallSignatureDeclaration' is not assignable to type 'FunctionLikeDeclaration'.
    Type 'CallSignatureDeclaration' is missing the following properties from type 'ArrowFunction': equalsGreaterThanToken, body, _expressionBrand, _functionLikeDeclarationBrand
TypeScript: 3 semantic errors
TypeScript: emit succeeded (with errors)
[23:32:42] 'pxtcompiler' errored after 6.02 s
[23:32:42] Error: TypeScript: Compilation failed
    at Output.mightFinish (C:\Users\cianb\Documents\repos\makecode-peter\pxt\node_modules\gulp-typescript\release\output.js:130:43)
    at C:\Users\cianb\Documents\repos\makecode-peter\pxt\node_modules\gulp-typescript\release\output.js:65:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[23:32:42] 'default' errored after 14 s
[23:32:42] The following tasks did not complete: pxtsim
[23:32:42] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pxt-core@5.33.5 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pxt-core@5.33.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cianb\AppData\Roaming\npm-cache\_logs\2020-02-05T12_32_42_492Z-debug.log

***
*** Build failed: local pxt-core build FAILED
Error: Exit code: 1 from cd node_modules/pxt-core; npm.cmd run build
    at ChildProcess.<anonymous> (C:\Users\cianb\Documents\repos\makecode-peter\pxt\built\nodeutil.js:85:24)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
***

building C:\Users\cianb\Documents\repos\makecode-peter\pxt-maker\node_modules\pxt-common-packages\sim...
[run] cd C:\Users\cianb\Documents\repos\makecode-peter\pxt-maker\node_modules\pxt-common-packages\sim; node ../node_modules/typescript/bin/tsc
../node_modules/pxt-core/built/pxtsim.d.ts(255,13): error TS1086: An accessor cannot be declared in an ambient context.
../node_modules/pxt-core/built/pxtsim.d.ts(1006,13): error TS1086: An accessor cannot be declared in an ambient context.
../node_modules/pxt-core/built/pxtsim.d.ts(1045,13): error TS1086: An accessor cannot be declared in an ambient context.
../node_modules/pxt-core/built/pxtsim.d.ts(1283,21): error TS1086: An accessor cannot be declared in an ambient context.
../node_modules/pxt-core/built/pxtsim.d.ts(1283,21): error TS7033: Property 'stoppedClass' implicitly has type 'any', because its get accessor lacks a return type annotation.
../node_modules/pxt-core/built/pxtsim.d.ts(1284,21): error TS1086: An accessor cannot be declared in an ambient context.
../node_modules/pxt-core/built/pxtsim.d.ts(1284,21): error TS7033: Property 'invalidatedClass' implicitly has type 'any', because its get accessor lacks a return type annotation.

***
*** Build failed: target build failed: Exit code: 2 from cd C:\Users\cianb\Documents\repos\makecode-peter\pxt-maker\node_modules\pxt-common-packages\sim; node ../node_modules/typescript/bin/tsc
Error: Exit code: 2 from cd C:\Users\cianb\Documents\repos\makecode-peter\pxt-maker\node_modules\pxt-common-packages\sim; node ../node_modules/typescript/bin/tsc
    at ChildProcess.<anonymous> (C:\Users\cianb\Documents\repos\makecode-peter\pxt\built\nodeutil.js:85:24)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

```

**Desktop (please complete the following information):**
 - OS:  Windows 10

**Comment by pelikhan** [comment]
Make sure to run npm install again. We’ve upgraded typescript

**Comment by wallarug** [comment]
I tried again and still get errors relating to typescript.   Just to make sure I also used all the official `Microsoft/` repositories and went ahead and added all the build tools to my computer (which I didn't need before to run pxt-maker).


**Console output (running custom pxt-maker):**

```
[run] cd C:\Users\cianb\Documents\repos\makecode-peter\pxt-maker\node_modules\pxt-common-packages\sim; node ../node_modules/typescript/bin/tsc
../node_modules/pxt-core/built/pxtsim.d.ts(255,13): error TS1086: An accessor cannot be declared in an ambient context.
../node_modules/pxt-core/built/pxtsim.d.ts(1006,13): error TS1086: An accessor cannot be declared in an ambient context.
../node_modules/pxt-core/built/pxtsim.d.ts(1045,13): error TS1086: An accessor cannot be declared in an ambient context.
../node_modules/pxt-core/built/pxtsim.d.ts(1283,21): error TS1086: An accessor cannot be declared in an ambient context.
../node_modules/pxt-core/built/pxtsim.d.ts(1283,21): error TS7033: Property 'stoppedClass' implicitly has type 'any', because its get accessor lac   ks a return type annotation.
../node_modules/pxt-core/built/pxtsim.d.ts(1284,21): error TS1086: An accessor cannot be declared in an ambient context.
../node_modules/pxt-core/built/pxtsim.d.ts(1284,21): error TS7033: Property 'invalidatedClass' implicitly has type 'any', because its get accessor    lacks a return type annotation.

***
*** Build failed: target build failed: Exit code: 2 from cd C:\Users\cianb\Documents\repos\makecode-peter\pxt-maker\node_modules\pxt-common-packag   es\sim; node ../node_modules/typescript/bin/tsc
Error: Exit code: 2 from cd C:\Users\cianb\Documents\repos\makecode-peter\pxt-maker\node_modules\pxt-common-packages\sim; node ../node_modules/typ   escript/bin/tsc
    at ChildProcess.<anonymous> (C:\Users\cianb\Documents\repos\makecode-peter\pxt\built\nodeutil.js:85:24)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
***
```


**Console output (running microsoft/pxt-maker unmodified):**

```
local pxt-core built.
building C:\Users\cianb\Documents\repos\makecode-latest\pxt-maker\node_modules\pxt-common-packages\sim...
[run] cd C:\Users\cianb\Documents\repos\makecode-latest\pxt-maker\node_modules\pxt-common-packages\sim; node ../node_modules/typescript/bin/tsc
../node_modules/pxt-core/built/pxtsim.d.ts(255,13): error TS1086: An accessor cannot be declared in an ambient context.
../node_modules/pxt-core/built/pxtsim.d.ts(1006,13): error TS1086: An accessor cannot be declared in an ambient context.
../node_modules/pxt-core/built/pxtsim.d.ts(1045,13): error TS1086: An accessor cannot be declared in an ambient context.
../node_modules/pxt-core/built/pxtsim.d.ts(1283,21): error TS1086: An accessor cannot be declared in an ambient context.
../node_modules/pxt-core/built/pxtsim.d.ts(1283,21): error TS7033: Property 'stoppedClass' implicitly has type 'any', because its get accessor lacks a return type annotation.
../node_modules/pxt-core/built/pxtsim.d.ts(1284,21): error TS1086: An accessor cannot be declared in an ambient context.
../node_modules/pxt-core/built/pxtsim.d.ts(1284,21): error TS7033: Property 'invalidatedClass' implicitly has type 'any', because its get accessor lacks a return type annotation.

***
*** Build failed: target build failed: Exit code: 2 from cd C:\Users\cianb\Documents\repos\makecode-latest\pxt-maker\node_modules\pxt-common-packages\sim; node ../node_modules/typescript/bin/tsc
Error: Exit code: 2 from cd C:\Users\cianb\Documents\repos\makecode-latest\pxt-maker\node_modules\pxt-common-packages\sim; node ../node_modules/typescript/bin/tsc
    at ChildProcess.<anonymous> (C:\Users\cianb\Documents\repos\makecode-latest\pxt\built\nodeutil.js:85:24)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
***


```

**Comment by riknoll** [comment]
@wallarug pull master and make sure you run gulp clean. This was a bug on Windows that should be fixed by https://github.com/microsoft/pxt/pull/6539

**Comment by pelikhan** [comment]
I have fixed the typescript version in common packages. Pull and npm install again.

**Comment by wallarug** [comment]
Excellent work @riknoll  and @pelikhan .  You have made me a happy developer again.  👍 😄 

It is all working as expected again now.
