### ISSUE TITLE
require('pxt-microbit') throws Error: Cannot find module 'pxt-microbit'

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#752]
method on Windows 10
```
npm init
npm install -save pxt-microbit
code index.js
node index.js
```
```
C:\Users\owen\Source\test>node index.js
{ Error: Cannot find module 'pxt-microbit'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\owen\Source\test\index.js:5:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }

```

index.js
```
"use strict";

const path = require('path');
try {
    const pxtMicrobit = require('pxt-microbit');
}catch (ex) {
    console.error(ex);
}
```

https://microbit-community.slack.com/archives/pxt/p1478859847000116

**Comment by OwenBrotherwood** [comment]
works again:
```
C:\Users\owen\Source\test>rmdir /s node_modules\pxt-core
node_modules\pxt-core, Are you sure (Y/N)? y

C:\Users\owen\Source\test>rmdir /s node_modules\pxt-microbit
node_modules\pxt-microbit, Are you sure (Y/N)? y

C:\Users\owen\Source\test>npm install
test@1.0.0 C:\Users\owen\Source\test
`-- pxt-microbit@0.6.11
  `-- pxt-core@0.5.68

npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

C:\Users\owen\Source\test>node index.js

C:\Users\owen\Source\test>
```
