### ISSUE TITLE
Reset crashes application 

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#804]
Resetting the project crashes application: 

main.js:7809 Unhandled rejection TypeError: workspace.resetAsync(...).catch(...).done is not a function
    at https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:1179:18
From previous event:
    at ProjectView.reset (https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:1174:12)
    at onClick (https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:1438:3435)
    at Object.ReactErrorUtils.invokeGuardedCallback (https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:48022:16)
    at executeDispatch (https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:41038:21)
    at Object.executeDispatchesInOrder (https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:41061:5)
    at executeDispatchesAndRelease (https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:40497:22)
    at executeDispatchesAndReleaseTopLevel (https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:40508:10)
    at Array.forEach (native)
    at forEachAccumulated (https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:54508:9)
    at Object.processEventQueue (https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:40713:7)
    at runEventQueueInBatch (https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:48048:18)
    at Object.handleTopLevel [as _handleTopLevel] (https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:48064:5)
    at handleTopLevelWithoutPath (https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:48162:24)
    at handleTopLevelImpl (https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:48142:3)
    at ReactDefaultBatchingStrategyTransaction.perform (https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:53979:20)
    at Object.batchedUpdates (https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:46765:19)
    at Object.batchedUpdates (https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:52046:20)
    at dispatchEvent (https://pxt.azureedge.net/blob/50e21afb1073e20bb00a08161a3379dccda41a26/main.js:48273:20)

**Comment by microsoftsam** [comment]
Reloading the page fixes things, and the workspace has been reset.

**Comment by pelikhan** [comment]
Looks good now.
