### ISSUE TITLE
'pxt' without arguments crashes

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#834]
```
[13:22 core]$ pxt
Using target PXT/microbit with build engine yotta
  Target dir:   /Users/michal/src/pxt-microbit
  PXT Core dir: /Users/michal/src/pxt
running 'pxt deploy' (run 'pxt help' for usage)
INTERNAL ERROR: Error: Command 'undefined' not found
    at CommandParser.parseCommand (/Users/michal/src/pxt/built/commandparser.js:39:19)
    at Object.mainCli (/Users/michal/src/pxt/built/pxt.js:77528:14)
```

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/commit/d28ec8a1e6d63eb79b949b7bd9a9b6fa207bc742
