### ISSUE TITLE
can't start open new project in micro:bit beta

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt#8849]
Repro steps:

1. Visit https://makecode.microbit.org/beta
2. Create a "New project"
3. give it a name
4. see that the project doesn't open and inspect console to see error:

```
pxtapp.js:1 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'hideSimButtons')
    at e.SimulatorDriver.createFrame (pxtapp.js:1:566060)
    at e.SimulatorDriver.preload (pxtapp.js:1:566608)
    at ae.internalLoadHeaderAsync (main.js:1:79380)
    at ae.loadHeaderAsync (main.js:1:79166)
    at async ae.createProjectAsync (main.js:1:99790)
createFrame @ pxtapp.js:1
preload @ pxtapp.js:1
internalLoadHeaderAsync @ main.js:1
loadHeaderAsync @ main.js:1
```

**Comment by abchatra** [comment]
Fixed by https://github.com/microsoft/pxt/commit/deb202367ccb549688366b275f771348ceba6f3f

Will be in /beta microbit in another 30 minutes or so.
