### ISSUE TITLE
simulator crash on missing shim

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#96]
We should have a nicer way to crash when a shim is missing (which happens when using packages).

```
pxtsim.js:1449 Simulator crashed, no error handler TypeError: pxsim.bluetooth.delimiters is not a function
    at Object.entryPoint [as fn] (eval at Runtime (http://localhost:3232/cdn/pxtsim.js:1536:18), <anonymous>:11:26)
    at loop (http://localhost:3232/cdn/pxtsim.js:1441:31)
    at topCall (http://localhost:3232/cdn/pxtsim.js:1497:17)
    at Runtime.run (http://localhost:3232/cdn/pxtsim.js:1537:47)
    at http://localhost:3232/cdn/pxtsim.js:110:25
    at r (http://localhost:3232/cdn/bluebird.min.js:31:7444)
    at r._settlePromiseFromHandler (http://localhost:3232/cdn/bluebird.min.js:30:12758)
    at r._settlePromise (http://localhost:3232/cdn/bluebird.min.js:30:13561)
    at r._settlePromiseCtx (http://localhost:3232/cdn/bluebird.min.js:30:14069)
    at r._drainQueue (http://localhost:3232/cdn/bluebird.min.js:29:3131)
    at r._drainQueues (http://localhost:3232/cdn/bluebird.min.js:29:3
```

**Comment by mmoskal** [comment]
We now show the error message and let the package author specify function body for use in simulator only https://www.pxt.io/simshim#simulator-implementations
